---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dovecot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dovecot
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      containers:
      - image: hkawabe/dovecot:latest
        name: dovecot
        volumeMounts:
        - name: mailbox
          mountPath: /home/vmail
        - name: config-volume
          mountPath: /etc/dovecot
        ports:
        - containerPort: 143
          protocol: TCP
      volumes:
      - name: mailbox
        persistentVolumeClaim:
          claimName: pvc-vmail
      - name: config-volume
        configMap:
          name: dovecot-config
      imagePullSecrets:
      - name: secdockerhub