---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dockerimage
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      name: dockerimage
  storageClassName: ""
