---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mail
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      name: vmail
  storageClassName: ""
