---
- name: update packages
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name: install packages
  apt:
    name: "{{ packages}}"
  vars:
    packages:
      - zsh
      - git
      - wget
      - screen
      - python-apt

- name: setup-cmdline
  replace:
    path: /boot/cmdline.txt
    regexp: '^(.* rootwait)$$'
    replace: '\1 cgroup_memory=1 cgroup_enable=memory cgroup_enable=cpuset'


- name: set /etc/hosts
  copy:
    src: hosts
    dest: /etc/hosts
    backup: yes 
    
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: set locale
  locale_gen:
    name: ja_JP.UTF-8

- name: Update resolv.conf file
  blockinfile:
    dest: /etc/resolv.conf
    insertbefore: nameserver
    content: search hkawabe.net

- name: Add a new group
  group:
    name: users
    gid: 1001
    state: present

- name: change password of pi user
  user:
    name: pi
    group: pi
    state: present
    shell: /bin/bash
    createhome: yes
    password: "{{ password | password_hash('sha512') }}"
    update_password: on_create
    generate_ssh_key: yes

- name: change permission of .ssh directory
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: '~pi/.ssh', mode: '0700' }
    - { path: '~pi', mode: '0700' }


- name: fix os-release file
  replace:
    dest: /etc/os-release
    regexp: 'ID=raspbian' 
    replace: 'ID=debian' 
    backup: yes

- name: use old iptables
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy

- name: disable swap
  systemd:
    name: dphys-swapfile.service
    enabled: no
    state: stopped
...
