---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mail
  labels:
    name: vmail
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.5.1
    path: /volume1/homes/vmail
