- name: install docker
  apt:
    deb: "{{ item }}"
  with_items:
    - https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/containerd.io_1.2.6-3_armhf.deb
    - https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/docker-ce-cli_19.03.5~3-0~debian-buster_armhf.deb
    - https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/docker-ce_19.03.5~3-0~debian-buster_armhf.deb

- name: modify docker.service
  blockinfile:
    path: /etc/systemd/system/docker.service
    block: |
      [Service]
      ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock
    create: yes

- name: start docker
  systemd:
    name: docker.service
    enabled: yes
    state: started
    daemon-reload: yes

- name: install docker-volume
  apt:
    deb: https://github.com/ContainX/docker-volume-netshare/releases/download/v0.35/docker-volume-netshare_0.35_armhf.deb

- name: install docker-volume systemd script
  get_url:
    url: https://github.com/ContainX/docker-volume-netshare/blob/v0.35/support/systemd/lib/systemd/system/docker-volume-netshare.service
    dest: /etc/systemd/system/docker-volume-netshare.serivce

- name: start docker-volume
  systemd:
    name: docker-volume-netshare
    enabled: yes
    state: started
    daemon-reload: yes
