- name: Raspberry Pi settings
  hosts: rpi
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - { role: common, tags: common }
    - { role: docker, tags: docker }

- name: install kubernetes
  hosts: rpi
  gather_facts: false
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - { role: k8s, tags: k8s }
    
- name: initialize k8s master
  hosts: master
  gather_facts: false
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - { role: k8s_init, tags: k8s_init }

- name: join k8s worker 
  gather_facts: false
  become: yes
  become_user: root
  become_method: sudo
