---
apiVersion: v1
kind: Service
metadata:
  name: imap
spec:
  type: NodePort
  ports:
  - name: "imap-port"
    protocol: "TCP"
    port: 143
    targetPort: 143
    nodePort: 30143
  selector:
    app: dovecot